import {
  CaseRecord,
  RiskAlert,
  Intervention,
  CounsellingSession,
  NotificationItem,
  AuditLogItem,
  UserConsent,
} from '@/types';

export const INITIAL_CASES: CaseRecord[] = [
  {
    id: 'CASE-002', // Primary demonstration case (Section 24 & 38): 38 -> 46 -> 57 -> 71 (Increasing) -> intervention -> 59 -> 44 (Improving)
    anonymizedCode: 'BEN-7821',
    registeredDate: '2026-01-14',
    state: 'Assam',
    district: 'Kamrup Metropolitan',
    stage: 'trial',
    assignedCounsellor: 'Dr. Ananya Sarma (Senior Clinical Counsellor)',
    currentScore: 71,
    previousScore: 57,
    baselineScore: 38,
    riskLevel: 'high',
    lastCheckInDate: '2026-09-26',
    nextFollowUpDate: '2026-09-27',
    priorityReason: 'Distress score surged +33 points from baseline (38 -> 71); fear increased, sleep concerns reported, engagement decreased',
    missedCheckInsCount: 1,
    language: 'as',
    communicationPreference: 'app',
    recentSignals: [
      'Fear increased (+3 points in recent check-in)',
      'Sleep concerns increased (severe insomnia 1/5)',
      'Distress increased (+33 points from personal baseline 38)',
      'Engagement decreased (1 missed check-in detected)',
    ],
    trendHistory: [
      { date: '2026-08-28', score: 38, eventNote: 'Initial personal baseline intake', isCheckIn: true },
      { date: '2026-09-08', score: 46, isCheckIn: true },
      { date: '2026-09-17', score: 57, eventNote: 'Trial witness summons received', isCheckIn: true },
      { date: '2026-09-26', score: 71, eventNote: 'High concern: fear & sleep distress spike', isCheckIn: true },
    ],
  },
  {
    id: 'CASE-001', // Section 24: 38 -> 40 -> 37 -> 39 (Status: Stable)
    anonymizedCode: 'BEN-4902',
    registeredDate: '2025-09-05',
    state: 'Jharkhand',
    district: 'Ranchi',
    stage: 'compensation',
    assignedCounsellor: 'Alok Toppo (Legal Welfare Officer)',
    currentScore: 39,
    previousScore: 37,
    baselineScore: 38,
    riskLevel: 'mild',
    lastCheckInDate: '2026-09-25',
    nextFollowUpDate: '2026-10-10',
    priorityReason: 'Stable status: historical trajectory (38 -> 40 -> 37 -> 39) within normal baseline variance',
    missedCheckInsCount: 0,
    language: 'hi',
    communicationPreference: 'sms',
    recentSignals: [
      'Consistent steady response pattern (38 -> 40 -> 37 -> 39)',
      'Indicators stay within individual baseline variance',
      'Routine periodic monitoring active',
    ],
    trendHistory: [
      { date: '2026-08-15', score: 38, eventNote: 'Intake baseline', isCheckIn: true },
      { date: '2026-08-29', score: 40, isCheckIn: true },
      { date: '2026-09-12', score: 37, isCheckIn: true },
      { date: '2026-09-25', score: 39, isCheckIn: true },
    ],
  },
  {
    id: 'CASE-003', // Section 24: 52 -> 49 -> 43 -> 36 (Status: Improving)
    anonymizedCode: 'BEN-6219',
    registeredDate: '2025-11-18',
    state: 'Odisha',
    district: 'Mayurbhanj',
    stage: 'rehabilitation',
    assignedCounsellor: 'Sunita Majhi (Rehabilitation Specialist)',
    currentScore: 36,
    previousScore: 43,
    baselineScore: 52,
    riskLevel: 'mild',
    lastCheckInDate: '2026-09-25',
    nextFollowUpDate: '2026-10-02',
    priorityReason: 'Improving trajectory: indicators decreased from 52 to 36 following rehabilitation linkage',
    missedCheckInsCount: 0,
    language: 'en',
    communicationPreference: 'app',
    recentSignals: [
      'Steady improving trajectory (52 -> 49 -> 43 -> 36)',
      'Sleep stability improved from troubled to moderate',
      'Active participation in livelihood support unit',
    ],
    trendHistory: [
      { date: '2026-08-20', score: 52, eventNote: 'Intake baseline assessment', isCheckIn: true },
      { date: '2026-08-30', score: 49, isCheckIn: true },
      { date: '2026-09-12', score: 43, eventNote: 'Vocational training enrollment', isCheckIn: true },
      { date: '2026-09-25', score: 36, eventNote: 'Self-help micro grant approved', isCheckIn: true },
    ],
  },
  {
    id: 'CASE-004', // Section 24: 35 -> 54 -> 69 -> intervention -> 55 -> 42 (Improving after intervention)
    anonymizedCode: 'BEN-8433',
    registeredDate: '2026-02-02',
    state: 'West Bengal',
    district: 'South 24 Parganas',
    stage: 'protection',
    assignedCounsellor: 'Pradeep Mukherjee (District Welfare Worker)',
    currentScore: 42,
    previousScore: 55,
    baselineScore: 35,
    riskLevel: 'mild',
    lastCheckInDate: '2026-09-26',
    nextFollowUpDate: '2026-10-05',
    priorityReason: 'Positive recovery: distress surged to 69, stabilized to 42 following emergency protection intervention',
    missedCheckInsCount: 0,
    language: 'bn',
    communicationPreference: 'ivrs',
    recentSignals: [
      'Trajectory: 35 -> 54 -> 69 -> [Intervention] -> 55 -> 42',
      'Protection escort mobilized; intimidation markers mitigated',
      'Recent well-being indicators show improvement',
    ],
    trendHistory: [
      { date: '2026-07-15', score: 35, eventNote: 'Baseline intake', isCheckIn: true },
      { date: '2026-08-05', score: 54, isCheckIn: true },
      { date: '2026-08-24', score: 69, eventNote: 'Threat reported near residence', isCheckIn: true },
      { date: '2026-09-02', score: 60, eventNote: 'Police protection & safe transit escort assigned', isCheckIn: false },
      { date: '2026-09-14', score: 55, isCheckIn: true },
      { date: '2026-09-26', score: 42, eventNote: 'Follow-up completed: indicators improved', isCheckIn: true },
    ],
  },
  {
    id: 'ATC-2026-00124',
    anonymizedCode: 'BEN-7821',
    registeredDate: '2026-01-14',
    state: 'Assam',
    district: 'Kamrup Metropolitan',
    stage: 'trial',
    assignedCounsellor: 'Dr. Ananya Sarma (Senior Clinical Counsellor)',
    currentScore: 68,
    previousScore: 42,
    baselineScore: 35,
    riskLevel: 'elevated',
    lastCheckInDate: '2026-09-25',
    nextFollowUpDate: '2026-09-28',
    priorityReason: 'Distress score surged +26 points following witness deposition notice; sleep disturbances reported',
    missedCheckInsCount: 0,
    language: 'as',
    communicationPreference: 'app',
    recentSignals: [
      'Elevated distress score (+26 pts over 7 days)',
      'Severe sleep disruption flagged in check-in responses',
      'Increased fear markers around scheduled court hearing',
      'Expressed desire for immediate counselling consultation',
    ],
    trendHistory: [
      { date: '2026-08-28', score: 32, eventNote: 'Initial baseline evaluation', isCheckIn: true },
      { date: '2026-09-03', score: 35, isCheckIn: true },
      { date: '2026-09-08', score: 38, isCheckIn: true },
      { date: '2026-09-12', score: 40, eventNote: 'Investigation report finalized', isCheckIn: true },
      { date: '2026-09-17', score: 42, isCheckIn: true },
      { date: '2026-09-21', score: 54, eventNote: 'Trial summons delivered to residence', isCheckIn: true },
      { date: '2026-09-25', score: 68, eventNote: 'Elevated distress indicators detected', isCheckIn: true },
    ],
  },
  {
    id: 'ATC-2026-00131',
    anonymizedCode: 'BEN-8433',
    registeredDate: '2026-02-02',
    state: 'West Bengal',
    district: 'South 24 Parganas',
    stage: 'investigation',
    assignedCounsellor: 'Pradeep Mukherjee (District Welfare Worker)',
    currentScore: 82,
    previousScore: 74,
    baselineScore: 48,
    riskLevel: 'high',
    lastCheckInDate: '2026-09-24',
    nextFollowUpDate: '2026-09-26',
    priorityReason: 'High concern: 2 consecutive missed check-ins followed by high fear responses; protection review recommended',
    missedCheckInsCount: 2,
    language: 'bn',
    communicationPreference: 'ivrs',
    recentSignals: [
      'Consecutive missed periodic check-ins (4 days silence)',
      'Perceived safety score dropped to lowest rating (1/5)',
      'Mentions intimidation near local transport hub',
      'Urgent protection & home visit recommended',
    ],
    trendHistory: [
      { date: '2026-08-27', score: 48, eventNote: 'FIR registered with special cell', isCheckIn: true },
      { date: '2026-09-02', score: 52, isCheckIn: true },
      { date: '2026-09-09', score: 55, isCheckIn: true },
      { date: '2026-09-14', score: 63, eventNote: 'Perpetrator bail hearing', isCheckIn: true },
      { date: '2026-09-19', score: 74, isCheckIn: true },
      { date: '2026-09-24', score: 82, eventNote: 'Safety threat reported to local desk', isCheckIn: true },
    ],
  },
  {
    id: 'ATC-2026-00142',
    anonymizedCode: 'BEN-6219',
    registeredDate: '2025-11-18',
    state: 'Odisha',
    district: 'Mayurbhanj',
    stage: 'rehabilitation',
    assignedCounsellor: 'Sunita Majhi (Rehabilitation Specialist)',
    currentScore: 34,
    previousScore: 41,
    baselineScore: 65,
    riskLevel: 'mild',
    lastCheckInDate: '2026-09-25',
    nextFollowUpDate: '2026-10-02',
    priorityReason: 'Positive trajectory: distress indicators down 31 points since livelihood training enrollment',
    missedCheckInsCount: 0,
    language: 'en',
    communicationPreference: 'app',
    recentSignals: [
      'Steady engagement across 4 consecutive check-ins',
      'Sleep stability improved from troubled to moderate',
      'Active participation in local micro-enterprise unit',
    ],
    trendHistory: [
      { date: '2026-08-20', score: 60, eventNote: 'Vocational counseling session', isCheckIn: true },
      { date: '2026-08-27', score: 54, isCheckIn: true },
      { date: '2026-09-04', score: 48, isCheckIn: true },
      { date: '2026-09-11', score: 41, isCheckIn: true },
      { date: '2026-09-18', score: 36, eventNote: 'First self-help grant disbursed', isCheckIn: true },
      { date: '2026-09-25', score: 34, isCheckIn: true },
    ],
  },
  {
    id: 'ATC-2026-00157',
    anonymizedCode: 'BEN-4902',
    registeredDate: '2025-09-05',
    state: 'Jharkhand',
    district: 'Ranchi',
    stage: 'compensation',
    assignedCounsellor: 'Alok Toppo (Legal Welfare Officer)',
    currentScore: 22,
    previousScore: 24,
    baselineScore: 58,
    riskLevel: 'stable',
    lastCheckInDate: '2026-09-23',
    nextFollowUpDate: '2026-10-15',
    priorityReason: 'Stable status: victim compensation award credited, routine monthly monitoring',
    missedCheckInsCount: 0,
    language: 'hi',
    communicationPreference: 'sms',
    recentSignals: [
      'Consistent stable response pattern over 45 days',
      'All 7 check-in markers indicate calm home environment',
      'Compensation stage verification verified by treasury',
    ],
    trendHistory: [
      { date: '2026-08-15', score: 36, isCheckIn: true },
      { date: '2026-08-29', score: 30, isCheckIn: true },
      { date: '2026-09-08', score: 26, eventNote: 'Welfare compensation sanction order', isCheckIn: true },
      { date: '2026-09-16', score: 24, isCheckIn: true },
      { date: '2026-09-23', score: 22, isCheckIn: true },
    ],
  },
  {
    id: 'ATC-2026-00168',
    anonymizedCode: 'BEN-9130',
    registeredDate: '2026-09-10',
    state: 'Bihar',
    district: 'Muzaffarpur',
    stage: 'complaint',
    assignedCounsellor: 'Dr. Rameshwar Pandey (Psychiatric Social Worker)',
    currentScore: 71,
    previousScore: 75,
    baselineScore: 75,
    riskLevel: 'elevated',
    lastCheckInDate: '2026-09-24',
    nextFollowUpDate: '2026-09-27',
    priorityReason: 'Freshly registered case under PoA Act; initial trauma assessment pending',
    missedCheckInsCount: 0,
    language: 'hi',
    communicationPreference: 'voice_call',
    recentSignals: [
      'High baseline distress following immediate incident reporting',
      'Severe social avoidance reported in initial intake',
      'Immediate crisis counseling scheduled',
    ],
    trendHistory: [
      { date: '2026-09-12', score: 78, eventNote: 'Complaint registered under PoA Act', isCheckIn: true },
      { date: '2026-09-18', score: 75, isCheckIn: true },
      { date: '2026-09-24', score: 71, eventNote: 'First home welfare assessment', isCheckIn: true },
    ],
  },
  {
    id: 'ATC-2026-00175',
    anonymizedCode: 'BEN-3391',
    registeredDate: '2026-04-12',
    state: 'Meghalaya',
    district: 'East Khasi Hills',
    stage: 'protection',
    assignedCounsellor: 'Grace Lyngdoh (Protection Support Officer)',
    currentScore: 19,
    previousScore: 23,
    baselineScore: 62,
    riskLevel: 'stable',
    lastCheckInDate: '2026-09-22',
    nextFollowUpDate: '2026-10-10',
    priorityReason: 'Safe relocation confirmed; victim reports high feeling of physical security',
    missedCheckInsCount: 0,
    language: 'kha',
    communicationPreference: 'app',
    recentSignals: [
      'Relocation to transit facility stable',
      'No threats reported over past 60 days',
      'Positive emotional baseline restored',
    ],
    trendHistory: [
      { date: '2026-08-10', score: 45, eventNote: 'Relocation order issued', isCheckIn: true },
      { date: '2026-08-25', score: 32, isCheckIn: true },
      { date: '2026-09-10', score: 23, eventNote: 'Local security audit completed', isCheckIn: true },
      { date: '2026-09-22', score: 19, isCheckIn: true },
    ],
  },
  {
    id: 'ATC-2026-00183',
    anonymizedCode: 'BEN-5012',
    registeredDate: '2026-03-30',
    state: 'Tamil Nadu',
    district: 'Madurai',
    stage: 'trial',
    assignedCounsellor: 'K. Balakrishnan (Senior Case Worker)',
    currentScore: 77,
    previousScore: 61,
    baselineScore: 40,
    riskLevel: 'high',
    lastCheckInDate: '2026-09-25',
    nextFollowUpDate: '2026-09-26',
    priorityReason: 'Defense cross-examination scheduled next week; rapid uptick in anxiety and sleeplessness',
    missedCheckInsCount: 1,
    language: 'ta',
    communicationPreference: 'voice_call',
    recentSignals: [
      'Anxiety markers spiked by 35% in recent audio check-in',
      'Expressed fear regarding public court exposure',
      'Special prosecutor accompaniment requested',
    ],
    trendHistory: [
      { date: '2026-08-15', score: 42, isCheckIn: true },
      { date: '2026-08-30', score: 45, isCheckIn: true },
      { date: '2026-09-12', score: 55, isCheckIn: true },
      { date: '2026-09-20', score: 61, eventNote: 'Court witness summons received', isCheckIn: true },
      { date: '2026-09-25', score: 77, eventNote: 'Defense cross-examination date posted', isCheckIn: true },
    ],
  },
  {
    id: 'ATC-2026-00192',
    anonymizedCode: 'BEN-7704',
    registeredDate: '2025-10-10',
    state: 'Manipur',
    district: 'Imphal West',
    stage: 'rehabilitation',
    assignedCounsellor: 'Th. Bembem Devi (District Welfare Counsellor)',
    currentScore: 28,
    previousScore: 31,
    baselineScore: 52,
    riskLevel: 'mild',
    lastCheckInDate: '2026-09-21',
    nextFollowUpDate: '2026-10-05',
    priorityReason: 'Education stipend disbursed for family dependents; gradual adaptation',
    missedCheckInsCount: 0,
    language: 'mni',
    communicationPreference: 'app',
    recentSignals: [
      'Steady mood stability',
      'Children enrolled in supportive day-care program',
    ],
    trendHistory: [
      { date: '2026-08-10', score: 40, isCheckIn: true },
      { date: '2026-08-25', score: 35, isCheckIn: true },
      { date: '2026-09-08', score: 31, isCheckIn: true },
      { date: '2026-09-21', score: 28, eventNote: 'Educational scholarship grant confirmed', isCheckIn: true },
    ],
  },
];

export const INITIAL_ALERTS: RiskAlert[] = [
  {
    id: 'ALT-1092',
    caseId: 'ATC-2026-00131',
    caseCode: 'BEN-8433',
    district: 'South 24 Parganas, West Bengal',
    riskLevel: 'high',
    title: 'High Concern: Significant Safety Distress & Missed Check-ins',
    reason: 'Two consecutive periodic check-ins missed followed by lowest reported safety score (1/5) and perceived intimidation.',
    timestamp: '2026-09-25 18:30',
    status: 'urgent',
    signals: [
      'Safety score dropped to 1/5',
      'Consecutive missed check-ins (4 days silence)',
      'Threat markers detected near transport node',
    ],
    assignedTo: 'Pradeep Mukherjee',
  },
  {
    id: 'ALT-1088',
    caseId: 'ATC-2026-00183',
    caseCode: 'BEN-5012',
    district: 'Madurai, Tamil Nadu',
    riskLevel: 'high',
    title: 'High Concern: Acute Anxiety Spike Prior to Cross-Examination',
    reason: 'Distress indicator increased from 61 to 77 within 5 days. Voice response indicates heightened panic regarding upcoming trial appearance.',
    timestamp: '2026-09-25 15:45',
    status: 'urgent',
    signals: [
      'Rapid uptick in linguistic fear markers (+35%)',
      'Sleep duration under 4 hours reported',
      'Trial witness protection requested',
    ],
    assignedTo: 'K. Balakrishnan',
  },
  {
    id: 'ALT-1081',
    caseId: 'ATC-2026-00124',
    caseCode: 'BEN-7821',
    district: 'Kamrup Metropolitan, Assam',
    riskLevel: 'elevated',
    title: 'Elevated Indicator: Trial Summons Distress Reaction',
    reason: 'Distress score increased from 42 to 68 over 7 days following formal court summons delivery. Sleeping difficulties flagged.',
    timestamp: '2026-09-25 11:20',
    status: 'pending',
    signals: [
      'Score surged +26 points above individual baseline',
      'Night-time insomnia and panic responses',
      'Requested callback from clinical counsellor',
    ],
    assignedTo: 'Dr. Ananya Sarma',
  },
  {
    id: 'ALT-1075',
    caseId: 'ATC-2026-00168',
    caseCode: 'BEN-9130',
    district: 'Muzaffarpur, Bihar',
    riskLevel: 'elevated',
    title: 'Elevated Indicator: New Intake Trauma Assessment Required',
    reason: 'Complaint registered recently. Individual reporting acute social avoidance and elevated distress indicator (71).',
    timestamp: '2026-09-24 16:10',
    status: 'pending',
    signals: [
      'High baseline score (71/100) on initial check-in',
      'Social avoidance score 4/5',
      'Needs in-person psychological first-aid visit',
    ],
    assignedTo: 'Dr. Rameshwar Pandey',
  },
  {
    id: 'ALT-1064',
    caseId: 'ATC-2026-00142',
    caseCode: 'BEN-6219',
    district: 'Mayurbhanj, Odisha',
    riskLevel: 'mild',
    title: 'Follow-Up Required: Livelihood Transition Check',
    reason: 'Scheduled 14-day check on vocational training adaptation. Overall indicators improving steadily.',
    timestamp: '2026-09-23 10:00',
    status: 'reviewed',
    signals: [
      'Distress indicator at 34 (stable improvement)',
      'Standard post-rehabilitation monitoring milestone',
    ],
    assignedTo: 'Sunita Majhi',
  },
];

export const INITIAL_INTERVENTIONS: Intervention[] = [
  {
    id: 'INT-501',
    caseId: 'ATC-2026-00124',
    category: 'counselling',
    title: 'Pre-Trial Anxiety Desensitization Tele-Counselling',
    description: 'Provide grounding techniques, court proceeding orientation, and emotional stabilization before witness testimony.',
    assignedProfessional: 'Dr. Ananya Sarma (Senior Clinical Counsellor)',
    scheduledDate: '2026-09-28',
    status: 'scheduled',
    outcomeNotes: 'Pending session',
    aiSuggested: true,
  },
  {
    id: 'INT-502',
    caseId: 'ATC-2026-00131',
    category: 'protection',
    title: 'Urgent Police Protection Review & Escort Protocol',
    description: 'Coordinate with Superintendent of Police special cell to review security around complainant transit corridor.',
    assignedProfessional: 'Inspector R. Bannerjee & Pradeep Mukherjee',
    scheduledDate: '2026-09-26',
    status: 'in_progress',
    outcomeNotes: 'Emergency mobile patrol deployed; safe shelter transfer evaluated.',
    aiSuggested: true,
  },
  {
    id: 'INT-503',
    caseId: 'ATC-2026-00183',
    category: 'legal',
    title: 'Special Public Prosecutor Pre-Trial Briefing',
    description: 'In-camera hearing request submission and vulnerable witness court deposition facilitation.',
    assignedProfessional: 'Adv. S. Ramanathan & K. Balakrishnan',
    scheduledDate: '2026-09-27',
    status: 'scheduled',
    outcomeNotes: 'In-camera trial petition drafted under Section 15A of SC/ST PoA Act.',
    aiSuggested: true,
  },
  {
    id: 'INT-504',
    caseId: 'ATC-2026-00142',
    category: 'rehabilitation',
    title: 'Micro-Enterprise Livelihood Grant Linkage',
    description: 'Connecting complainant with District Industries Centre self-employment scheme and credit subsidy.',
    assignedProfessional: 'Sunita Majhi',
    scheduledDate: '2026-09-18',
    status: 'completed',
    outcomeNotes: 'Beneficiary enrolled in district handloom cooperative; first tranche released.',
    aiSuggested: false,
  },
  {
    id: 'INT-505',
    caseId: 'ATC-2026-00157',
    category: 'financial',
    title: 'Interim Victim Compensation Treasury Verification',
    description: 'Expediting district compensation board disbursement under Central Victim Compensation Fund.',
    assignedProfessional: 'Alok Toppo',
    scheduledDate: '2026-09-16',
    status: 'completed',
    outcomeNotes: '₹4,50,000 direct bank transfer credited successfully.',
    aiSuggested: false,
  },
];

export const INITIAL_COUNSELLING_SESSIONS: CounsellingSession[] = [
  {
    id: 'CNS-301',
    caseId: 'ATC-2026-00124',
    counsellorName: 'Dr. Ananya Sarma',
    date: '2026-09-20',
    modality: 'tele',
    durationMinutes: 45,
    summaryNotes: 'Complainant expressed significant trepidation regarding encountering accused family in court compound. Provided cognitive stabilization exercises and explained witness protection shield options.',
    followUpRecommended: true,
    followUpDue: '2026-09-28',
  },
  {
    id: 'CNS-302',
    caseId: 'ATC-2026-00131',
    counsellorName: 'Pradeep Mukherjee',
    date: '2026-09-18',
    modality: 'home_visit',
    durationMinutes: 60,
    summaryNotes: 'Home visit conducted with local female constable. Family reported intimidation near grocery shop. Assessed immediate physical safety and initiated safe house relocation review.',
    followUpRecommended: true,
    followUpDue: '2026-09-26',
  },
  {
    id: 'CNS-303',
    caseId: 'ATC-2026-00142',
    counsellorName: 'Sunita Majhi',
    date: '2026-09-11',
    modality: 'in_person',
    durationMinutes: 40,
    summaryNotes: 'Positive progress noted. Complainant demonstrated high self-efficacy in vocational skill training. Sleep quality markedly improved.',
    followUpRecommended: false,
    followUpDue: '2026-10-02',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NOTIF-01',
    type: 'alert',
    title: 'High Concern Alert Generated',
    message: 'Case ATC-2026-00131 has been flagged for immediate human review due to consecutive missed check-ins and threat signals.',
    timestamp: '15 mins ago',
    read: false,
    linkCaseId: 'ATC-2026-00131',
  },
  {
    id: 'NOTIF-02',
    type: 'check_in',
    title: 'New Check-In Received',
    message: 'Case ATC-2026-00124 completed a periodic check-in. Distress score updated to 68 (Elevated concern).',
    timestamp: '1 hour ago',
    read: false,
    linkCaseId: 'ATC-2026-00124',
  },
  {
    id: 'NOTIF-03',
    type: 'appointment',
    title: 'Upcoming Counselling Session',
    message: 'Tele-counselling session scheduled for Case ATC-2026-00124 on Sep 28 at 11:00 AM.',
    timestamp: '3 hours ago',
    read: true,
    linkCaseId: 'ATC-2026-00124',
  },
  {
    id: 'NOTIF-04',
    type: 'intervention',
    title: 'Protection Review Approved',
    message: 'District Officer approved emergency patrol deployment for South 24 Parganas district case.',
    timestamp: 'Yesterday',
    read: true,
    linkCaseId: 'ATC-2026-00131',
  },
  {
    id: 'NOTIF-05',
    type: 'system',
    title: 'National Quarterly Compliance Report Ready',
    message: 'Q3 Atrocity Victim Welfare & Monitoring Summary Report is available for download.',
    timestamp: '2 days ago',
    read: true,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'AUD-9912',
    timestamp: '2026-09-26 01:20:45',
    actor: 'Dr. Ananya Sarma (Counsellor)',
    actorRole: 'counsellor',
    action: 'CASE_PROFILE_ACCESS',
    resource: 'ATC-2026-00124',
    district: 'Kamrup Metropolitan, Assam',
    purpose: 'Pre-trial distress assessment review and intervention scheduling',
  },
  {
    id: 'AUD-9911',
    timestamp: '2026-09-25 18:32:10',
    actor: 'System AI Engine',
    actorRole: 'automated_service',
    action: 'ALERT_GENERATION',
    resource: 'ALT-1092 / ATC-2026-00131',
    district: 'South 24 Parganas, West Bengal',
    purpose: 'Automated distress early-warning generation (non-clinical screening)',
  },
  {
    id: 'AUD-9910',
    timestamp: '2026-09-25 16:04:18',
    actor: 'Shri Bikash Sen (District Officer)',
    actorRole: 'district_officer',
    action: 'INTERVENTION_APPROVAL',
    resource: 'INT-502 / ATC-2026-00131',
    district: 'South 24 Parganas, West Bengal',
    purpose: 'Authorized emergency protection review and police liaison',
  },
  {
    id: 'AUD-9909',
    timestamp: '2026-09-24 14:15:30',
    actor: 'Alok Toppo (Welfare Officer)',
    actorRole: 'counsellor',
    action: 'COMPENSATION_STAGE_UPDATE',
    resource: 'ATC-2026-00157',
    district: 'Ranchi, Jharkhand',
    purpose: 'Treasury disbursement confirmation logged under CVCF guidelines',
  },
  {
    id: 'AUD-9908',
    timestamp: '2026-09-23 11:05:00',
    actor: 'National Admin (Directorate)',
    actorRole: 'national_admin',
    action: 'AGGREGATE_REPORT_EXPORT',
    resource: 'ALL_STATES_ANONYMIZED_SUMMARY',
    district: 'National Repository',
    purpose: 'Quarterly review of victim support timelines without PII exposure',
  },
];

export const INITIAL_CONSENT: UserConsent = {
  voiceAnalysis: true,
  automatedReminders: true,
  longitudinalTracking: true,
  emergencyContactShared: true,
  lastUpdated: '2026-09-15',
};

// District aggregates for non-sensitive geographic map & admin view
export interface DistrictAggregate {
  district: string;
  state: string;
  activeCases: number;
  elevatedRiskCases: number;
  counsellorsActive: number;
  interventionsCompleted: number;
  avgResponseHours: number;
}

export const DISTRICT_AGGREGATES: DistrictAggregate[] = [
  { district: 'Kamrup Metropolitan', state: 'Assam', activeCases: 28, elevatedRiskCases: 6, counsellorsActive: 7, interventionsCompleted: 42, avgResponseHours: 3.4 },
  { district: 'South 24 Parganas', state: 'West Bengal', activeCases: 44, elevatedRiskCases: 11, counsellorsActive: 9, interventionsCompleted: 68, avgResponseHours: 2.8 },
  { district: 'Mayurbhanj', state: 'Odisha', activeCases: 19, elevatedRiskCases: 3, counsellorsActive: 5, interventionsCompleted: 35, avgResponseHours: 4.1 },
  { district: 'Ranchi', state: 'Jharkhand', activeCases: 31, elevatedRiskCases: 5, counsellorsActive: 8, interventionsCompleted: 53, avgResponseHours: 3.1 },
  { district: 'Muzaffarpur', state: 'Bihar', activeCases: 36, elevatedRiskCases: 9, counsellorsActive: 6, interventionsCompleted: 49, avgResponseHours: 3.9 },
  { district: 'East Khasi Hills', state: 'Meghalaya', activeCases: 14, elevatedRiskCases: 2, counsellorsActive: 4, interventionsCompleted: 26, avgResponseHours: 2.5 },
  { district: 'Madurai', state: 'Tamil Nadu', activeCases: 38, elevatedRiskCases: 8, counsellorsActive: 8, interventionsCompleted: 59, avgResponseHours: 3.0 },
  { district: 'Imphal West', state: 'Manipur', activeCases: 21, elevatedRiskCases: 4, counsellorsActive: 5, interventionsCompleted: 31, avgResponseHours: 3.6 },
  { district: 'Aizawl', state: 'Mizoram', activeCases: 12, elevatedRiskCases: 1, counsellorsActive: 4, interventionsCompleted: 22, avgResponseHours: 2.2 },
  { district: 'Kokrajhar', state: 'Assam (BTR)', activeCases: 23, elevatedRiskCases: 5, counsellorsActive: 6, interventionsCompleted: 38, avgResponseHours: 3.5 },
];

export interface StateAggregate {
  state: string;
  totalCases: number;
  activeCases: number;
  elevatedRisk: number;
  interventionsCompleted: number;
  counsellingSlaPercentage: number;
}

export const STATE_AGGREGATES: StateAggregate[] = [
  { state: 'Assam', totalCases: 210, activeCases: 84, elevatedRisk: 18, interventionsCompleted: 164, counsellingSlaPercentage: 94.2 },
  { state: 'West Bengal', totalCases: 340, activeCases: 142, elevatedRisk: 32, interventionsCompleted: 278, counsellingSlaPercentage: 91.8 },
  { state: 'Tamil Nadu', totalCases: 290, activeCases: 118, elevatedRisk: 24, interventionsCompleted: 235, counsellingSlaPercentage: 96.0 },
  { state: 'Bihar', totalCases: 310, activeCases: 130, elevatedRisk: 29, interventionsCompleted: 240, counsellingSlaPercentage: 88.5 },
  { state: 'Jharkhand', totalCases: 195, activeCases: 76, elevatedRisk: 14, interventionsCompleted: 155, counsellingSlaPercentage: 92.4 },
  { state: 'Odisha', totalCases: 180, activeCases: 68, elevatedRisk: 12, interventionsCompleted: 148, counsellingSlaPercentage: 93.6 },
  { state: 'Meghalaya', totalCases: 75, activeCases: 26, elevatedRisk: 4, interventionsCompleted: 62, counsellingSlaPercentage: 97.5 },
  { state: 'Manipur', totalCases: 115, activeCases: 48, elevatedRisk: 11, interventionsCompleted: 88, counsellingSlaPercentage: 89.1 },
  { state: 'Mizoram', totalCases: 52, activeCases: 18, elevatedRisk: 2, interventionsCompleted: 44, counsellingSlaPercentage: 98.0 },
];
