/**
 * Feature Registry for Distress Monitoring & Early-Warning ML Pipeline
 * Central registry documenting normalized feature definitions, ranges, and sources.
 */

export interface FeatureDefinition {
  name: string;
  displayName: string;
  type: 'numeric' | 'categorical' | 'boolean';
  range: [number, number] | string[];
  source: 'check_ins' | 'distress_assessments' | 'case_history' | 'alerts' | 'voice_features';
  description: string;
  normalizedRange?: [number, number];
}

export const FEATURE_REGISTRY: Record<string, FeatureDefinition> = {
  fear_score: {
    name: 'fear_score',
    displayName: 'Reported Fear & Dread',
    type: 'numeric',
    range: [1, 5],
    normalizedRange: [0, 1],
    source: 'check_ins',
    description: 'Self-reported acute fear or hyper-vigilance score from recent check-in.',
  },
  sleep_score: {
    name: 'sleep_score',
    displayName: 'Sleep Disturbance Inversion',
    type: 'numeric',
    range: [1, 5],
    normalizedRange: [0, 1],
    source: 'check_ins',
    description: 'Inverted sleep quality indicator (higher represents worse sleep disturbance / insomnia).',
  },
  stress_score: {
    name: 'stress_score',
    displayName: 'Somatic Stress Index',
    type: 'numeric',
    range: [1, 5],
    normalizedRange: [0, 1],
    source: 'check_ins',
    description: 'Subjective somatic stress or physical tension indicator.',
  },
  withdrawal_score: {
    name: 'withdrawal_score',
    displayName: 'Social Withdrawal & Avoidance',
    type: 'numeric',
    range: [1, 5],
    normalizedRange: [0, 1],
    source: 'check_ins',
    description: 'Degree of social avoidance, isolation, or difficulty engaging with family/community.',
  },
  safety_concern_score: {
    name: 'safety_concern_score',
    displayName: 'Safety Vulnerability',
    type: 'numeric',
    range: [1, 5],
    normalizedRange: [0, 1],
    source: 'check_ins',
    description: 'Inverted perceived personal physical or legal safety concern.',
  },
  engagement_score: {
    name: 'engagement_score',
    displayName: 'App/Service Engagement Ratio',
    type: 'numeric',
    range: [0, 1],
    normalizedRange: [0, 1],
    source: 'case_history',
    description: 'Proportion of scheduled check-ins completed in the last 30 days.',
  },
  help_seeking_score: {
    name: 'help_seeking_score',
    displayName: 'Explicit Help Seeking Flag',
    type: 'boolean',
    range: [0, 1],
    source: 'check_ins',
    description: 'Binary signal indicating user explicitly asked for callback or intervention.',
  },
  missed_checkin_count: {
    name: 'missed_checkin_count',
    displayName: 'Consecutive Missed Check-Ins',
    type: 'numeric',
    range: [0, 10],
    normalizedRange: [0, 1],
    source: 'case_history',
    description: 'Count of consecutive scheduled monitoring windows missed without notice.',
  },
  checkin_frequency: {
    name: 'checkin_frequency',
    displayName: 'Cadence Frequency (days)',
    type: 'numeric',
    range: [1, 30],
    normalizedRange: [0, 1],
    source: 'case_history',
    description: 'Average days elapsed between consecutive check-in events.',
  },
  baseline_indicator: {
    name: 'baseline_indicator',
    displayName: 'Personal Baseline Score',
    type: 'numeric',
    range: [0, 100],
    normalizedRange: [0, 1],
    source: 'distress_assessments',
    description: 'Calculated individual baseline score from historical quiet-period check-ins.',
  },
  current_indicator: {
    name: 'current_indicator',
    displayName: 'Current Distress Indicator',
    type: 'numeric',
    range: [0, 100],
    normalizedRange: [0, 1],
    source: 'distress_assessments',
    description: 'Most recent multi-factor composite distress indicator score (0–100).',
  },
  baseline_deviation: {
    name: 'baseline_deviation',
    displayName: 'Baseline Delta (+/- pts)',
    type: 'numeric',
    range: [-100, 100],
    normalizedRange: [-1, 1],
    source: 'distress_assessments',
    description: 'Current indicator minus personal baseline (positive indicates elevated distress).',
  },
  trend_slope: {
    name: 'trend_slope',
    displayName: 'Trajectory Linear Slope',
    type: 'numeric',
    range: [-10, 10],
    normalizedRange: [-1, 1],
    source: 'distress_assessments',
    description: 'Ordinary least-squares linear slope across the last 5 observations.',
  },
  trend_velocity: {
    name: 'trend_velocity',
    displayName: 'Velocity of Indicator Change',
    type: 'numeric',
    range: [-50, 50],
    normalizedRange: [-1, 1],
    source: 'distress_assessments',
    description: 'Point-to-point change divided by time interval in days.',
  },
  recent_change: {
    name: 'recent_change',
    displayName: 'Last Delta (Score difference)',
    type: 'numeric',
    range: [-100, 100],
    normalizedRange: [-1, 1],
    source: 'distress_assessments',
    description: 'Delta between current score and immediate previous score.',
  },
  rolling_mean_7d: {
    name: 'rolling_mean_7d',
    displayName: '7-Day Rolling Mean',
    type: 'numeric',
    range: [0, 100],
    normalizedRange: [0, 1],
    source: 'distress_assessments',
    description: 'Weighted moving average of scores over the prior 7 days.',
  },
  rolling_mean_30d: {
    name: 'rolling_mean_30d',
    displayName: '30-Day Rolling Mean',
    type: 'numeric',
    range: [0, 100],
    normalizedRange: [0, 1],
    source: 'distress_assessments',
    description: 'Weighted moving average of scores over the prior 30 days.',
  },
  rolling_mean_90d: {
    name: 'rolling_mean_90d',
    displayName: '90-Day Rolling Mean',
    type: 'numeric',
    range: [0, 100],
    normalizedRange: [0, 1],
    source: 'distress_assessments',
    description: 'Quarterly moving average establishing longitudinal resting baseline.',
  },
  volatility: {
    name: 'volatility',
    displayName: 'Score Volatility (Std Dev)',
    type: 'numeric',
    range: [0, 30],
    normalizedRange: [0, 1],
    source: 'distress_assessments',
    description: 'Standard deviation across prior observations measuring emotional turbulence.',
  },
  number_of_recent_alerts: {
    name: 'number_of_recent_alerts',
    displayName: 'Prior 30d Alert Count',
    type: 'numeric',
    range: [0, 10],
    normalizedRange: [0, 1],
    source: 'alerts',
    description: 'Total automated alerts generated for this case within the last 30 days.',
  },
  intervention_recency: {
    name: 'intervention_recency',
    displayName: 'Days Since Last Intervention',
    type: 'numeric',
    range: [0, 365],
    normalizedRange: [0, 1],
    source: 'case_history',
    description: 'Days elapsed since a caseworker intervention or counselling session occurred.',
  },
  followup_status: {
    name: 'followup_status',
    displayName: 'Scheduled Follow-up Due Flag',
    type: 'boolean',
    range: [0, 1],
    source: 'case_history',
    description: 'Flag indicating whether a caseworker follow-up is overdue or pending.',
  },
};
